#!/usr/bin/env bash
# Generates a .env file with random secrets for local Docker Compose runs.
# Safe to re-run — will not overwrite an existing .env unless --force is passed.
set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [[ -f "$ENV_FILE" ]] && [[ "${1:-}" != "--force" ]]; then
  echo ".env already exists. Pass --force to regenerate."
  exit 0
fi

POSTGRES_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%&' </dev/urandom | head -c 32)
JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh — do not commit this file.

POSTGRES_USER=capitec
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}

# Optional: override allowed CORS origins (comma-separated).
# Leave blank when running behind nginx on the same host.
CORS_ALLOWED_ORIGINS=
EOF

echo "Created $ENV_FILE"
echo ""
echo "Default demo credentials:"
echo "  Admin : admin@capitec.co.za / Admin@123"
echo "  User  : user@capitec.co.za  / User@123"
